### ISSUE TITLE
have design AngularJs web app & want to integrate Meteor in that 

### ISSUE THREAD

**Issue by varshaudasi** [ParamountVentures/meteor-ionic-starter#2]
Please help me.. getting issues related to meteor..
these are the errors..

Uncaught ReferenceError: Mongo is not defined(anonymous function) @ app.ng.js:1
routes.js:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ routes.js:1
CarouselCtrl.ng.js:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ CarouselCtrl.ng.js:1
product-description-controller.ng.js:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ product-description-controller.ng.js:1
contact-us-controller.ng.js:3 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ contact-us-controller.ng.js:3
product-gallery-controller.ng.js:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ product-gallery-controller.ng.js:1
SearchController.ng.js:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ SearchController.ng.js:1
SearchService.ng.js:1 Uncaught ReferenceError: Meteor is not defined(anonymous function) @ SearchService.ng.js:1
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module myStore due to:
Error: [$injector:nomod] Module 'myStore' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.5/$injector/nomod?p0=myStore
at REGEX_STRING_REGEXP (https://bakery-corner-varshaudasi.c9.io:8080/js/angular.js:68:12)
at https://bakery-corner-varshaudasi.c9.io:8080/js/angular.js:1983:17
at ensure (https://bakery-corner-varshaudasi.c9.io:8080/js/angular.js:1907:38)
at module (https://bakery-corner-varshaudasi.c9.io:8080/js/angular.js:1981:14)
at https://bakery-corner-varshaudasi.c9.io:8080/js/angular.js:4385:22
at forEach (https://bakery-corner-varshaudasi.c9.io:8080/js/angular.js:336:20)
at loadModules (https://bakery-corner-varshaudasi.c9.io:8080/js/angular.js:4369:5)
at createInjector (https://bakery-corner-varshaudasi.c9.io:8080/js/angular.js:4294:11)
at doBootstrap (https://bakery-corner-varshaudasi.c9.io:8080/js/angular.js:1655:20)
at bootstrap (https://bakery-corner-varshaudasi.c9.io:8080/js/angular.js:1676:12)
http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=myStore&p1=Error%3A…%2F%2Fbakery-corner-varshaudasi.c9.io%3A8080%2Fjs%2Fangular.js%3A1676%3A12)REGEX_STRING_REGEXP @ angular.js:68(anonymous function) @ angular.js:4408forEach @ angular.js:336loadModules @ angular.js:4369createInjector @ angular.js:4294doBootstrap @ angular.js:1655bootstrap @ angular.js:1676angularInit @ angular.js:1570(anonymous function) @ angular.js:28683m.Callbacks.j @ jquery-1.11.3.min.js:2m.Callbacks.k.fireWith @ jquery-1.11.3.min.js:2m.extend.ready @ jquery-1.11.3.min.js:2J @ jquery-1.11.3.min.js:2
16 minutes ago

Enter your message here

**Comment by varshaudasi** [comment]
please help me.. got stucked

**Comment by varshaudasi** [comment]
How would you approach adding MeteorJS to an existing AngularJS.. what all changes are required can you help me.. how to display json data..  n how to add packages.. plz help me.. i want some login n  shopping cart functionality of meteor.. for that my angular app must be run with meteor.. need your help urigo.. plz help me..

**Comment by varshaudasi** [comment]
plz help me to integrate meteor into angular Js app.. http://angular-meteor.com/ tutorials are not helping with this.. urigo i need your help
